### PR TITLE
added all classes and tested them

### PR DESCRIPTION
**Pull request by RLudchenko**

### CODE REVIEW

**Comment by RLudchenko** [comment]
@Tarabarnik can you tell me please what's wrong with the solution?

**Comment by Tarabarnik** [comment]
> @Tarabarnik can you tell me please what's wrong with the solution?

you did not make all points from task. read the [readme](https://github.com/mate-academy/jv-oop#jv-oop) carefully

**Comment by RLudchenko** [comment]
@Tarabarnik that's strange, there is no solution at all for some reason, I will push it again

**Comment by RLudchenko** [comment]
done

**Pull request closed without merging**
